site:
  title: MixQL Project
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://mixql.org
  start_page: users-guide::overview.adoc
  robots: allow
#urls:
#  html_extension_style: drop
content:
  sources:
    - url: https://github.com/mixql/mixql-docs
      start_paths: docs/contributors-guide , docs/users-guide
    - url: https://github.com/mixql/mixql-core
      branches: [develop]
      start_path: docs
    - url: https://github.com/mixql/mixql-platform
      branches: [main]
      start_path: docs
    - url: https://github.com/mixql/mixql-platform
      branches: [main]
      start_path: mixql-protobuf/docs
    - url: https://github.com/mixql/mixql-platform
      branches: [main]
      start_path: mixql-cluster/docs
    - url: https://github.com/mixql/mixql-platform
      branches: [main]
      start_path: mixql-engine/docs
    - url: https://github.com/mixql/mixql-platform
      branches: [master]
      start_path: mixql-platform-demo/docs
    - url: https://github.com/mixql/mixql-platform
      branches: [main]
      start_path: engines/mixql-engine-stub/docs
    - url: https://github.com/mixql/mixql-platform
      branches: [main]
      start_path: engines/mixql-engine-stub-local/docs
    - url: https://github.com/mixql/mixql-platform
      branches: [main]
      start_path: engines/mixql-engine-sqlite/docs
    - url: https://github.com/mixql/mixql-platform
      branches: [main]
      start_path: engines/mixql-engine-sqlite-local/docs
    - url: https://github.com/mixql/mixql-test-env
      branches: [ main, branch-0.4.0 ]
      start_path: docs
      # updated develop

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./ui-src

output:
  clean: true
  dir: ./public

runtime:
  fetch: true
antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true