site:
  title: MixQL Project
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://mixql.org
  start_page: users-guide::index.adoc
  robots: allow
#urls:
#  html_extension_style: drop
content:
  sources:
    - url: https://github.com/mixql/mixql-docs
      start_paths: docs/contributors-guide , docs/users-guide
    - url: https://github.com/mixql/mixql-core
      branches: [develop]
      start_path: docs
    - url: https://github.com/mixql/mixql-protobuf
      branches: [main]
      start_path: docs
    - url: https://github.com/mixql/mixql-cluster
      branches: [main]
      start_path: docs
    - url: https://github.com/mixql/mixql-engine
      branches: [main]
      start_path: docs
    - url: https://github.com/mixql/mixql-engine-stub
      branches: [main]
      start_path: docs
    - url: https://github.com/mixql/mixql-engine-sqlite
      branches: [main]
      start_path: docs
    - url: https://github.com/mixql/mixql-platform-demo
      branches: [master]
      start_path: docs


ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./ui-src

output:
  clean: true
  dir: ./public

runtime:
  fetch: true
antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true