site:
  title: MixQL Project
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://mixql.org
  start_page: users-guide::index.adoc
  robots: allow
#urls:
#  html_extension_style: drop
content:
  sources:
    #  For local "author mode" builds check out this antora playbook project
    #  and the site project next to one another and uncomment the next lines and comment out the other - url
    - url: .
      start_paths: docs/users-guide, docs/contributors-guide
    - url: mixql-core
      branches: [develop]
      start_path: docs
    - url: mixql-platform
      branches: [main]
      start_path: mixql-protobuf/docs
    - url: mixql-platform
      branches: [main]
      start_path: mixql-cluster/docs
    - url: mixql-platform
      branches: [main]
      start_path: mixql-engine/docs
    - url: mixql-platform
      branches: [master]
      start_path: mixql-platform-demo/docs
    - url: mixql-platform
      branches: [main]
      start_path: engines/mixql-engine-stub/docs
    - url: mixql-platform
      branches: [main]
      start_path: engines/mixql-engine-stub-local/docs
    - url: mixql-platform
      branches: [main]
      start_path: engines/mixql-engine-sqlite/docs
    - url: mixql-platform
      branches: [main]
      start_path: engines/mixql-engine-sqlite-local/docs
    - url: mixql-test-env
      branches: [main]
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./ui-src
output:
  clean: true
  dir: ./public

runtime:
  fetch: true
antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true
